language: node_js
node_js: '6'
script:
  - npm run build
  - travis_retry npm run travis
sudo: false
cache:
  directories:
    - node_modules
addons:
  sauce_connect:
    username: "quill"
    access_key: "adc0c0cf-221b-46f1-81b9-a4429b722c2e"
env:
  matrix:
    - BROWSER=ios-latest
